stages:
  - test
  - build

sonarqube-check:
  stage: test
  image: 
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0"
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script: 
    - sonar-scanner
  allow_failure: true
  only:
   - develop

docker_build:
  image: docker:20
  stage: build
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - DOCKER_UPLOAD=[[ "$CI_COMMIT_REF_NAME" == "develop" ]] || [[ "$CI_COMMIT_REF_NAME" == "main" ]]
    - echo $DOCKER_UPLOAD
    - TAG=$CI_REGISTRY_IMAGE:$(([[ $DOCKER_UPLOAD == "true" ]] && (echo $CI_COMMIT_REF_NAME)) || echo develop)'
    - echo $TAG
    - docker pull $TAG || true
    - docker build --cache-from $TAG --tag $TAG .
    - $DOCKER_UPLOAD && docker push $TAG
  only:
    - merge_requests
    - develop
    - main
  
