stages:
  - test
  - build

#sonarqube-check:
#  stage: test
#  image: 
#    name: sonarsource/sonar-scanner-cli:latest
###    entrypoint: [""]
#  variables:
#    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
#    GIT_DEPTH: "0"
#  cache:
#    key: "${CI_JOB_NAME}"
#    paths:
#      - .sonar/cache
#  script: 
#    - sonar-scanner
#  allow_failure: true
#  only:
#    - main

docker_build:
  image: docker:20
  stage: build
  variables:
    TAG: "$CI_REGISTRY_IMAGE/birdazzone-api"
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - export
    - docker pull $TAG:latest || true
    - docker build --cache-from $TAG:latest --tag $TAG:latest .
    - docker push $TAG:latest

