// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "GNU AFFERO GENERAL PUBLIC LICENSE",
            "url": "https://www.gnu.org/licenses/agpl-3.0.en.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/hello": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "test"
                ],
                "summary": "Test your connection to birdazzone API",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/tvgames": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tvgames"
                ],
                "summary": "Get all TV games",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Game"
                            }
                        }
                    }
                }
            }
        },
        "/tvgames/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tvgames"
                ],
                "summary": "Get TV game",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID to search",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Game"
                        }
                    }
                }
            }
        },
        "/tvgames/{id}/attempts": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tvgames"
                ],
                "summary": "Retrieve game's attempts",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Game to query",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Page-model_Tweet"
                        }
                    },
                    "404": {
                        "description": "game id not found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/tvgames/{id}/attempts/stats": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tvgames"
                ],
                "summary": "Retrieve game's attempts' frequencies",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Game to query",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.ChartEntry"
                            }
                        }
                    },
                    "404": {
                        "description": "game id not found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/tvgames/{id}/results": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tvgames"
                ],
                "summary": "Retrieve game's number of successes and failures",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Game to query",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.BooleanChart"
                        }
                    },
                    "404": {
                        "description": "game id not found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/tvgames/{id}/solution": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tvgames"
                ],
                "summary": "Retrieve game's solution",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Game to query",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "game id not found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.BooleanChart": {
            "type": "object",
            "properties": {
                "negatives": {
                    "type": "integer",
                    "minimum": 0,
                    "example": 318
                },
                "positives": {
                    "type": "integer",
                    "minimum": 0,
                    "example": 209
                }
            }
        },
        "model.ChartEntry": {
            "type": "object",
            "properties": {
                "absolute_frequency": {
                    "type": "integer",
                    "minimum": 0,
                    "example": 34
                },
                "value": {
                    "type": "string",
                    "example": "parola"
                }
            }
        },
        "model.Game": {
            "type": "object",
            "properties": {
                "hashtag": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "model.Metrics": {
            "type": "object",
            "properties": {
                "like_count": {
                    "type": "integer",
                    "minimum": 0,
                    "example": 122
                },
                "reply_count": {
                    "type": "integer",
                    "minimum": 0,
                    "example": 42
                },
                "retweet_count": {
                    "type": "integer",
                    "minimum": 0,
                    "example": 15
                }
            }
        },
        "model.Page-model_Tweet": {
            "type": "object",
            "properties": {
                "entries": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Tweet"
                    }
                },
                "number_of_pages": {
                    "type": "integer",
                    "minimum": 1
                }
            }
        },
        "model.Tweet": {
            "type": "object",
            "properties": {
                "author": {
                    "$ref": "#/definitions/model.User"
                },
                "created_at": {
                    "type": "string",
                    "format": "date-time"
                },
                "metrics": {
                    "$ref": "#/definitions/model.Metrics"
                },
                "text": {
                    "type": "string",
                    "example": "Hello, world!"
                }
            }
        },
        "model.User": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "example": "Mario Rossi"
                },
                "profile_image_url": {
                    "type": "string"
                },
                "username": {
                    "type": "string",
                    "example": "mariorossi"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Birdazzone API",
	Description:      "API implementation for the Software Engineering (90106) project for the academic year 2022/23 at the University of Bologna.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
